version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: order_status
        tests:
          - accepted_values:
                values: ['delivered', 'shipped', 'canceled', 'invoiced', 'processing', 'approved', 'unavailable', 'created']

  - name: stg_reviews
    columns:
      - name: review_score
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]